CREATE TABLE IF NOT EXISTS `osh_open_project_source` (
    `id` bigint NOT NULL AUTO_INCREMENT COMMENT '主键ID',
    `source_name` varchar(100) NOT NULL COMMENT '项目源名称',
    `github_owner` varchar(100) NOT NULL COMMENT 'GitHub账号或组织',
    `github_url` varchar(500) NOT NULL COMMENT 'GitHub主页地址',
    `source_type` varchar(20) NOT NULL DEFAULT 'user' COMMENT '来源类型：user/org',
    `access_token` varchar(500) DEFAULT NULL COMMENT 'GitHub访问令牌（可选）',
    `enabled` tinyint NOT NULL DEFAULT 1 COMMENT '是否启用：0-禁用，1-启用',
    `sync_status` tinyint NOT NULL DEFAULT 0 COMMENT '同步状态：0-未同步，1-成功，2-失败',
    `last_sync_time` datetime DEFAULT NULL COMMENT '最后同步时间',
    `last_sync_message` varchar(500) DEFAULT NULL COMMENT '最后同步信息',
    `repo_count` int NOT NULL DEFAULT 0 COMMENT '最近一次同步仓库数量',
    `remark` varchar(500) DEFAULT NULL COMMENT '备注',
    `create_time` datetime DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    `create_by` bigint DEFAULT NULL COMMENT '创建人',
    `update_time` datetime DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    `update_by` bigint DEFAULT NULL COMMENT '更新人',
    `delete_flag` tinyint NOT NULL DEFAULT 0 COMMENT '逻辑删除：0-未删除，1-已删除',
    PRIMARY KEY (`id`),
    UNIQUE KEY `uk_github_owner` (`github_owner`, `delete_flag`),
    KEY `idx_enabled` (`enabled`),
    KEY `idx_delete_flag` (`delete_flag`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_as_cs COMMENT='开源项目GitHub项目源表';

CREATE TABLE IF NOT EXISTS `osh_open_project_contributor` (
    `id` bigint NOT NULL AUTO_INCREMENT COMMENT '主键ID',
    `project_id` bigint NOT NULL COMMENT '开源项目ID',
    `github_account` varchar(100) NOT NULL COMMENT 'GitHub账号',
    `wechat_name` varchar(100) DEFAULT NULL COMMENT '微信名称',
    `contributor_type` varchar(20) NOT NULL DEFAULT 'contributor' COMMENT '贡献人类型：primary/contributor/collaborator',
    `contributions` int NOT NULL DEFAULT 0 COMMENT '贡献次数',
    `avatar_url` varchar(500) DEFAULT NULL COMMENT 'GitHub头像',
    `profile_url` varchar(500) DEFAULT NULL COMMENT 'GitHub主页',
    `source` varchar(20) NOT NULL DEFAULT 'github' COMMENT '来源：github/manual',
    `editable` tinyint NOT NULL DEFAULT 1 COMMENT '是否允许编辑：0-否，1-是',
    `sort_order` int NOT NULL DEFAULT 0 COMMENT '排序',
    `create_time` datetime DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    `create_by` bigint DEFAULT NULL COMMENT '创建人',
    `update_time` datetime DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    `update_by` bigint DEFAULT NULL COMMENT '更新人',
    `delete_flag` tinyint NOT NULL DEFAULT 0 COMMENT '逻辑删除：0-未删除，1-已删除',
    PRIMARY KEY (`id`),
    UNIQUE KEY `uk_project_github` (`project_id`, `github_account`),
    KEY `idx_project_id` (`project_id`),
    KEY `idx_github_account` (`github_account`),
    KEY `idx_delete_flag` (`delete_flag`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_as_cs COMMENT='开源项目贡献人表';

ALTER TABLE `osh_open_project`
    ADD COLUMN `source_id` bigint DEFAULT NULL COMMENT '项目源ID' AFTER `last_sync_time`,
    ADD COLUMN `github_repo_id` bigint DEFAULT NULL COMMENT 'GitHub仓库ID' AFTER `source_id`,
    ADD COLUMN `github_owner` varchar(100) DEFAULT NULL COMMENT 'GitHub账号或组织' AFTER `github_repo_id`,
    ADD COLUMN `github_repo_name` varchar(100) DEFAULT NULL COMMENT 'GitHub仓库名称' AFTER `github_owner`,
    ADD COLUMN `default_branch` varchar(100) DEFAULT NULL COMMENT '默认分支' AFTER `github_repo_name`,
    ADD COLUMN `language` varchar(100) DEFAULT NULL COMMENT '主要语言' AFTER `default_branch`,
    ADD COLUMN `license_name` varchar(100) DEFAULT NULL COMMENT '开源协议' AFTER `language`,
    ADD COLUMN `homepage` varchar(500) DEFAULT NULL COMMENT '项目主页' AFTER `license_name`,
    ADD UNIQUE KEY `uk_github_repo_id` (`github_repo_id`),
    ADD KEY `idx_source_id` (`source_id`),
    ADD KEY `idx_github_owner` (`github_owner`);
